name: pragya_hamali_app
description: Hamali tracker for Pragya Products
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.13.1
  shared_preferences: ^2.2.3
    supabase_flutter: ^2.8.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
